/**
 * Random silly first + last names in a 1960s ski-lodge vibe for the splash screen.
 */

const FIRST = [
  'Bunky',
  'Mitzi',
  'Skip',
  'Buffy',
  'Chip',
  'Biff',
  'Corky',
  'Dizzy',
  'Moon',
  'Storm',
  'Dusty',
  'Rusty',
  'Bitsy',
  'Midge',
  'Gigi',
  'Tad',
  'Twinkles',
  'Bunny',
  'Babs',
  'Myrtle',
  'Mabel',
  'Eustace',
  'Elmer',
  'Otis',
  'Vern',
  'Orville',
  'Cletus',
  'Festus',
  'Roscoe',
  'Doyle',
  'Hubert',
  'Prudence',
  'Fifi',
  'Kiki',
  'Mugsy',
  'Zippy',
  'Groovy',
  'Sassy',
  'Snooky',
  'Muffy',
  'Bifford',
  'Trixie',
];

const LAST = [
  'Winterbottom',
  'McGillacuddy',
  'Pamplemousse',
  'Schnitzelhuber',
  'Frothington',
  'Crabtree',
  'Bottoms',
  'Gingersnap',
  'Fairweather',
  'Picklesworth',
  'Snowplow',
  'Iceberg',
  'Mogulmeister',
  'Slalomski',
  'Crabapple',
  'Wobblewick',
  'Fuzznoggle',
  'Thunderpants',
  'Woolybottom',
  'Snickerdoodle',
  'Vanderlay',
  'Hosenpfeffer',
  'von Powderkeg',
  'Kneebiter',
  'Glockenspiel',
  'VanSchuss',
  'Schnellfahren',
  'Powderbauer',
  'Zipline',
  'Schussboomer',
  'Puffinstuff',
  'Wigglesworth',
  'Bumbershoot',
  'Flapjack',
  'Toboggan',
  'Piste',
];

export function pickRandomSixtiesName() {
  const f = FIRST[Math.floor(Math.random() * FIRST.length)];
  const l = LAST[Math.floor(Math.random() * LAST.length)];
  return `${f} ${l}`;
}
